version: '3.8'

services:
  novitai-patent-mcp:
    build: .
    ports:
      - "8001:8001"
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8001
      - ENVIRONMENT=docker
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s




